# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_dsym_destination  = "../TrashOut.ipa"
app_ipa_destination   = "../TrashOut.app.dSYM.zip"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(text: "Changelog: ")
    build_number = incremented_build_number
    set_build_number(build_number)
    build_app(project: "TrashOut.xcodeproj", scheme: "TrashOut-Prod", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(changelog: changelog)

    add_git_tag(tag: "i#{build_number}")
    push_git_tags
  end

  after_all do |lane|
    File.delete(app_dsym_destination)
    File.delete(app_ipa_destination)
  end

  def latest_build_number_from_tag
    sh "git tag -l | xargs git tag -d && git fetch --tags"
      last_tag = last_git_tag(pattern: "i[0-9]*").to_s
      build_number = last_tag.gsub("i", "").to_i
      puts(build_number)
      build_number.to_s
  end

  def set_build_number(buildNumber)
    set_info_plist_value(path: "./TrashOut/Info-Prod.plist", key: "CFBundleVersion", value: buildNumber)
  end

  def incremented_build_number
    sh "git tag -l | xargs git tag -d && git fetch --tags"
      last_tag = last_git_tag(pattern: "i[0-9]*").to_s
      build_number = last_tag.gsub("i", "").to_i + 1
      puts(build_number)
      build_number.to_s
  end
end
